/* Auto-generated by AuthSystem - 2026-05-06T01:02:35.813Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_51ecb9e2-6b3',
  apiKey: 'ak_production_7b6cb680ca871b1c45d63a2ebd574134'
};
