/* Auto-generated by AuthSystem - 2026-05-03T07:52:37.303Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_51ecb9e2-6b3',
  apiKey: 'ak_development_e1e31da2b1ab7d22df1adb891497421b'
};
