/* Auto-generated by AuthSystem - 2026-08-01T22:22:21.702Z */
import { createClient } from '@supabase/supabase-js';
import { requireSupabaseAnonKey, requireSupabaseUrl } from './supabaseRuntime';

export const supabase = createClient(requireSupabaseUrl(), requireSupabaseAnonKey());
