/* Auto-generated by AuthSystem - 2026-05-13T07:17:48.645Z */
import { getEnvVariable } from '../services/envConfigService';

function resolveEnvValue(key: string): string {
  return (getEnvVariable(key) || (import.meta.env[key] as string | undefined) || '').trim();
}

export function getSupabaseUrl(): string {
  return resolveEnvValue('VITE_SUPABASE_URL').replace(/\/+$/, '');
}

export function getSupabaseAnonKey(): string {
  return resolveEnvValue('VITE_SUPABASE_ANON_KEY');
}

export function requireSupabaseUrl(): string {
  const value = getSupabaseUrl();
  if (!value || !/^https?:\/\//i.test(value)) {
    throw new Error('VITE_SUPABASE_URL no está configurada correctamente');
  }
  return value;
}

export function requireSupabaseAnonKey(): string {
  const value = getSupabaseAnonKey();
  if (!value) {
    throw new Error('VITE_SUPABASE_ANON_KEY no está configurada correctamente');
  }
  return value;
}
