/* Auto-generated by AuthSystem - 2026-06-11T04:00:52.950Z */
declare global {
  interface Window {
    __ENV__?: Record<string, string>;
  }
}

const DEFAULT_ENV_CONFIG_URL = 'https://ffihaeatoundrjzgtpzk.supabase.co/functions/v1/get-env';
const DEFAULT_ENV_CONFIG_ACCESS_KEY = '4a63305a316f04fe2acf33b2b63135925bd3a0523c1fd453a42fbf1fc49e6240';
const DEFAULT_SUPABASE_URL = 'https://sfqtmnncgiqkveaoqckt.supabase.co';
const DEFAULT_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcXRtbm5jZ2lxa3ZlYW9xY2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MDEyNDMsImV4cCI6MjA3NTM3NzI0M30.n2yaYrfHDLAFePP1tA3-250P6bgKmf696fYJFHfRZaQ';

class EnvConfigService {
  private loaded = false;
  private loadPromise: Promise<void> | null = null;

  async loadConfig(): Promise<void> {
    if (this.loaded) return;
    if (this.loadPromise) return this.loadPromise;

    this.loadPromise = this.fetchConfig().finally(() => {
      this.loadPromise = null;
    });

    return this.loadPromise;
  }

  private getFallbackVariables(): Record<string, string> {
    return {
      VITE_SUPABASE_URL: (import.meta.env.VITE_SUPABASE_URL as string | undefined) || DEFAULT_SUPABASE_URL,
      VITE_SUPABASE_ANON_KEY: (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) || DEFAULT_SUPABASE_ANON_KEY,
      ...(window.__ENV__ || {})
    };
  }

  private applyVariables(variables: Record<string, string>) {
    window.__ENV__ = {
      ...this.getFallbackVariables(),
      ...variables
    };
    this.loaded = true;
  }

  private async fetchConfig(): Promise<void> {
    const configuredUrl = (import.meta.env.VITE_ENV_CONFIG_URL as string | undefined)?.trim();
    const configuredAccessKey = (import.meta.env.VITE_ENV_CONFIG_ACCESS_KEY as string | undefined)?.trim()
      || DEFAULT_ENV_CONFIG_ACCESS_KEY;

    const candidates = [
      '/get-env',
      configuredUrl,
      DEFAULT_ENV_CONFIG_URL
    ].filter((value, index, array): value is string => !!value && array.indexOf(value) === index);

    for (const url of candidates) {
      try {
        const response = await fetch(url, {
          method: 'GET',
          headers: configuredAccessKey
            ? {
                'X-Access-Key': configuredAccessKey,
                'Content-Type': 'application/json'
              }
            : {
                'Content-Type': 'application/json'
              }
        });

        if (!response.ok) {
          throw new Error('Config response ' + response.status);
        }

        const payload = await response.json();
        const variables = payload?.variables && typeof payload.variables === 'object'
          ? payload.variables
          : payload;

        if (!variables || typeof variables !== 'object' || !Object.keys(variables).length) {
          throw new Error('No variables returned by ' + url);
        }

        this.applyVariables(variables as Record<string, string>);
        return;
      } catch (error) {
        console.warn('No se pudo cargar configuración desde', url, error);
      }
    }

    this.applyVariables({});
  }

  getVariable(key: string): string {
    return (window.__ENV__?.[key] || (import.meta.env[key] as string | undefined) || '').trim();
  }
}

export const envConfigService = new EnvConfigService();

export function getEnvVariable(key: string): string {
  return envConfigService.getVariable(key);
}
