/* Auto-generated by AuthSystem - 2026-08-22T21:39:03.675Z */
export const ipService = {
  async getClientIP() {
    try {
      const ipResponse = await fetch('https://api.ipify.org?format=json');
      const { ip } = await ipResponse.json();
      return ip;
    } catch (error) {
      return '0.0.0.0';
    }
  }
};
