/* Auto-generated by AuthSystem - 2026-07-20T22:30:28.480Z */
export const ipService = {
  async getClientIP() {
    try {
      const ipResponse = await fetch('https://api.ipify.org?format=json');
      const { ip } = await ipResponse.json();
      console.log('Detected client IP:', ip);
      return ip;
    } catch (error) {
      console.error('Error getting client IP:', error);
      return '0.0.0.0';
    }
  }
};
