/* Auto-generated by AuthSystem - 2026-08-02T01:26:53.751Z */
import { supabase } from '../lib/supabase';

export const rolesService = {
  async getRolesByApplication(internalAppId: string) {
    try {
      const { data, error } = await supabase
        .from('application_roles')
        .select('*')
        .eq('application_id', internalAppId)
        .order('display_name');

      if (error) {
        throw error;
      }

      return data || [];
    } catch (error) {
      return [];
    }
  },

  async getAvailableRolesForRegistration(internalAppId: string) {
    try {
      // Try with both columns first
      let { data, error } = await supabase
        .from('application_roles')
        .select('*')
        .eq('application_id', internalAppId)
        .order('display_name');

      // If columns exist, filter in JS (safer than SQL)
      if (data) {
        // Filter by available_for_registration if it exists
        const filtered = data.filter(role => {
          // If column doesn't exist, show all roles
          if (role.hasOwnProperty('available_for_registration')) {
            return role.available_for_registration === true;
          }
          // If column doesn't exist, show all non-admin roles or default roles
          return role.is_default === true || role.name !== 'admin';
        });

        return filtered || [];
      }

      if (error) {
        return [];
      }

      return [];
    } catch (error) {
      return [];
    }
  }
};
