/* Auto-generated by AuthSystem - 2026-08-22T21:39:03.675Z */
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import './index.css';
import { envConfigService } from './services/envConfigService';

async function bootstrap() {
  try {
    await envConfigService.loadConfig();
  } catch (error) {
  }

  const { default: App } = await import('./App');

  ReactDOM.createRoot(document.getElementById('root')!).render(
    <React.StrictMode>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </React.StrictMode>
  );
}

bootstrap();
