/* Auto-generated by AuthSystem - 2026-06-11T03:16:24.319Z */
import React, { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { CheckCircle, AlertCircle, Shield, ArrowRight } from 'lucide-react';
import { requireSupabaseAnonKey, requireSupabaseUrl } from '../../lib/supabaseRuntime';

const CALLBACK_PROCESSING_PREFIX = 'auth_callback_processing';
const CALLBACK_PROCESSED_PREFIX = 'auth_callback_processed';

function buildCallbackStorageKey(prefix: string, applicationId: string, code: string) {
  return prefix + ':' + (applicationId || 'unknown') + ':' + code;
}

function decodeBase64Url(value: string) {
  const normalized = value.replace(/-/g, '+').replace(/_/g, '/');
  const padded = normalized + '='.repeat((4 - (normalized.length % 4)) % 4);
  return atob(padded);
}

function decodeJwtClaims(token: string) {
  const tokenParts = token.split('.');
  if (tokenParts.length !== 3) {
    throw new Error('Formato de token inválido');
  }

  return JSON.parse(decodeBase64Url(tokenParts[1]));
}

export default function CallbackHandler() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const [status, setStatus] = useState<'loading' | 'success' | 'error'>('loading');
  const [message, setMessage] = useState('Procesando autenticación...');
  useEffect(() => {
    const run = async () => {
      try {
        const code = searchParams.get('code');
        const applicationId = searchParams.get('application_id') || searchParams.get('app_id') || '';
        const supabaseUrl = requireSupabaseUrl();
        const supabaseAnonKey = requireSupabaseAnonKey();

        if (!code) {
          throw new Error('No se encontró un código de autenticación válido en la URL');
        }

        if (!supabaseUrl || !supabaseAnonKey) {
          throw new Error('Supabase no está configurado');
        }

        window.history.replaceState({}, document.title, window.location.pathname);

        const storageApplicationId = applicationId || 'unknown';
        const processingKey = buildCallbackStorageKey(CALLBACK_PROCESSING_PREFIX, storageApplicationId, code);
        const processedKey = buildCallbackStorageKey(CALLBACK_PROCESSED_PREFIX, storageApplicationId, code);

        if (sessionStorage.getItem(processedKey) === '1') {
          setStatus('success');
          setMessage('Esta autenticaciÃ³n ya fue procesada. Redirigiendo...');
          setTimeout(() => {
            navigate('/login', { replace: true });
          }, 1200);
          return;
        }

        if (sessionStorage.getItem(processingKey) === '1') {
          setStatus('loading');
          setMessage('Procesando autenticaciÃ³n...');
          return;
        }

        sessionStorage.setItem(processingKey, '1');

        const response = await fetch(supabaseUrl + '/functions/v1/auth-exchange-code', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + supabaseAnonKey,
            'apikey': supabaseAnonKey
          },
          body: JSON.stringify(applicationId ? { code, application_id: applicationId } : { code })
        });

        const result = await response.json();
        if (!response.ok || !result.success) {
          throw new Error(result?.error?.message || 'No se pudo completar el intercambio de código');
        }

        const data = result.data || {};
        sessionStorage.setItem('auth_token', data.access_token || '');
        sessionStorage.setItem('refresh_token', data.refresh_token || '');
        const claims = decodeJwtClaims(String(data.access_token || ''));
        sessionStorage.setItem('user_data', JSON.stringify({
          id: claims.sub || '',
          email: claims.email || '',
          name: claims.name || '',
          role: claims.role || 'user',
          roles: Array.isArray(claims.roles) ? claims.roles : (claims.role ? [claims.role] : ['user']),
          permissions: claims.permissions || {},
          permissions_hierarchy: claims.permissions_hierarchy || {},
          metadata: claims.user_metadata || {},
          tenant: claims.tenant || null,
          subscription: claims.subscription || null,
          license: claims.license || null,
          has_access: claims.has_access,
          available_plans: claims.available_plans || [],
        }));
        sessionStorage.setItem('application_data', JSON.stringify({
          id: claims.app_id || applicationId || '',
          name: claims.app_name || '',
          domain: claims.app_domain || '',
          environment: claims.environment || null,
        }));

        sessionStorage.setItem(processedKey, '1');
        sessionStorage.removeItem(processingKey);

        setStatus('success');
        setMessage('Autenticación exitosa. Redirigiendo...');

        setTimeout(() => {
          navigate('/login', { replace: true });
        }, 1500);
      } catch (error: any) {
        const code = searchParams.get('code');
        const applicationId = searchParams.get('application_id') || searchParams.get('app_id');
        if (code && applicationId) {
          const processingKey = buildCallbackStorageKey(CALLBACK_PROCESSING_PREFIX, applicationId || 'unknown', code);
          sessionStorage.removeItem(processingKey);
        }

        setStatus('error');
        setMessage(error.message || 'Error procesando la autenticación');
      }
    };

    run();
  }, [navigate, searchParams]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-xl border border-gray-200 p-8 max-w-md w-full text-center">
        {status === 'loading' && (
          <>
            <div className="w-16 h-16 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Procesando autenticación...</h2>
            <p className="text-gray-600">Por favor espera mientras validamos tu sesión</p>
          </>
        )}

        {status === 'success' && (
          <>
            <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <CheckCircle className="w-8 h-8 text-green-500" />
            </div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">¡Autenticación Exitosa!</h2>
            <p className="text-gray-600 mb-4">{message}</p>
            <div className="mt-6 flex items-center justify-center space-x-2 text-sm text-gray-500">
              <Shield className="w-4 h-4" />
              <span>Sesión segura establecida</span>
            </div>
          </>
        )}

        {status === 'error' && (
          <>
            <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <AlertCircle className="w-8 h-8 text-red-500" />
            </div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Error de Autenticación</h2>
            <p className="text-gray-600 mb-6">{message}</p>

            <button
              onClick={() => navigate('/login', { replace: true })}
              className="bg-blue-500 hover:bg-blue-600 text-white px-6 py-2 rounded-lg flex items-center space-x-2 mx-auto transition-colors"
            >
              <span>Intentar de nuevo</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </>
        )}
      </div>
    </div>
  );
}