/* Auto-generated by AuthSystem - 2026-08-02T01:26:53.751Z */
import React, { useEffect, useState } from 'react';
import BrandedPublicAuth from './BrandedPublicAuth';
import { applicationService } from '../../services/applicationService';
import { supabase } from '../../lib/supabase';
import { requireSupabaseAnonKey, requireSupabaseUrl } from '../../lib/supabaseRuntime';
import { useSearchParams } from 'react-router-dom';

interface PublicAuthRouterProps {
  appId: string;
  formType: string;
}

export default function PublicAuthRouter({ appId, formType }: PublicAuthRouterProps) {
  const [appData, setAppData] = useState<any>(null);
  const [apiKey, setApiKey] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [searchParams] = useSearchParams();

  const validFormType = ['login', 'register', 'reset-password'].includes(formType)
    ? formType as 'login' | 'register' | 'reset-password'
    : 'login';

  useEffect(() => {
    const loadApplicationData = async () => {
      try {
        setLoading(true);

        // Get API key from URL first
        const apiKeyFromUrl = searchParams.get('api_key');
        if (apiKeyFromUrl) {
          setApiKey(apiKeyFromUrl);
        } else {
        }

        try {
          const { data: app, error: appError } = await supabase
            .from('applications')
            .select('*')
            .eq('application_id', appId)
            .single();

          if (appError || !app) {
            setError('Application not found');
            return;
          }

          try {
            const branding = await applicationService.getBranding(app.id);
            setAppData({
              ...app,
              branding: branding || {}
            });
          } catch (brandingError) {
            setAppData({
              ...app,
              branding: {}
            });
          }


        } catch (supabaseError) {
          setError('Failed to connect to database');
        }

      } catch (error) {
        setError('Failed to load application');
      } finally {
        setLoading(false);
      }
    };

    loadApplicationData();
  }, [appId, searchParams]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Error</h1>
          <p className="text-gray-600">{error}</p>
        </div>
      </div>
    );
  }

  const decodeBase64Url = (value: string) => {
    const normalized = value.replace(/-/g, '+').replace(/_/g, '/');
    const padded = normalized + '='.repeat((4 - (normalized.length % 4)) % 4);
    return atob(padded);
  };

  const decodeJwtClaims = (token: string) => {
    const tokenParts = String(token || '').split('.');
    if (tokenParts.length !== 3) {
      throw new Error('Formato de token invÃ¡lido');
    }

    return JSON.parse(decodeBase64Url(tokenParts[1]));
  };

  const storeAuthSessionFromTokens = (tokenData: any) => {
    if (!tokenData?.access_token) return null;

    const claims = decodeJwtClaims(tokenData.access_token);
    const roles = Array.isArray(claims.roles)
      ? claims.roles
      : claims.role
        ? [claims.role]
        : ['user'];

    sessionStorage.setItem('auth_token', tokenData.access_token);
    sessionStorage.setItem('refresh_token', tokenData.refresh_token || '');
    sessionStorage.setItem('user_data', JSON.stringify({
      id: claims.sub || '',
      email: claims.email || '',
      name: claims.name || '',
      role: claims.role || roles[0] || 'user',
      roles,
      permissions: claims.permissions || {},
      permissions_hierarchy: claims.permissions_hierarchy || {},
      metadata: claims.user_metadata || {},
      created_at: claims.user_created_at || null,
      tenant_id: claims.tenant_id || null,
      tenant_name: claims.tenant_name || null,
      tenant: claims.tenant || null,
      subscription: claims.subscription || null,
      license: claims.license || null,
      has_access: claims.has_access,
      available_plans: claims.available_plans || null,
      environment: claims.environment || null,
      last_login: new Date().toISOString()
    }));
    sessionStorage.setItem('application_data', JSON.stringify({
      id: claims.app_id || appId,
      name: claims.app_name || '',
      domain: claims.app_domain || '',
      environment: claims.environment || null
    }));

    if (typeof claims.exp === 'number') {
      sessionStorage.setItem('token_expires_at', new Date(claims.exp * 1000).toISOString());
    }

    return claims;
  };

  const handleAuthSubmit = async (formData: any) => {
    try {
      const urlParams = new URLSearchParams(window.location.search);
      const callbackUrl = urlParams.get('callback_url') || urlParams.get('redirect_uri');
      const channel = urlParams.get('channel') || (callbackUrl && /^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(callbackUrl) && !/^https?:/i.test(callbackUrl) ? 'mobile' : 'web');
      const state = urlParams.get('state');
      const codeChallenge = urlParams.get('code_challenge');
      const codeChallengeMethod = urlParams.get('code_challenge_method');

      // Get client IP
      const ipResponse = await fetch('https://api.ipify.org?format=json');
      const ipData = await ipResponse.json();
      const clientIp = ipData.ip;

      const supabaseUrl = requireSupabaseUrl();
      const supabaseAnonKey = requireSupabaseAnonKey();
      const apiBaseUrl = `${supabaseUrl}/functions/v1`;


      let endpoint = '';
      let payload: any = {};

      switch (validFormType) {
        case 'login':
          endpoint = `${apiBaseUrl}/auth-login`;
          payload = {
            email: formData.email,
            password: formData.password,
            application_id: appId,
            api_key: apiKey,
            callback_url: channel === 'web' ? callbackUrl : undefined,
            redirect_uri: callbackUrl,
            channel,
            state: state || undefined,
            code_challenge: channel === 'mobile' ? codeChallenge || undefined : undefined,
            code_challenge_method: channel === 'mobile' ? codeChallengeMethod || undefined : undefined,
            client_ip: clientIp
          };
          break;
        case 'register':
          if (formData.password !== formData.confirmPassword) {
            throw new Error('Las contraseñas no coinciden');
          }
          endpoint = `${apiBaseUrl}/auth-register`;
          payload = {
            email: formData.email,
            password: formData.password,
            name: formData.name,
            application_id: appId,
            api_key: apiKey,
            callback_url: channel === 'web' ? callbackUrl : undefined,
            redirect_uri: callbackUrl,
            channel,
            state: state || undefined,
            code_challenge: channel === 'mobile' ? codeChallenge || undefined : undefined,
            code_challenge_method: channel === 'mobile' ? codeChallengeMethod || undefined : undefined,
            role: formData.role || undefined,
            client_ip: clientIp
          };
          break;
        case 'reset-password':
          endpoint = `${apiBaseUrl}/auth-reset-password`;
          payload = {
            email: formData.email,
            application_id: appId,
            api_key: apiKey,
            redirect_uri: callbackUrl,
            client_ip: clientIp
          };
          break;
      }


      // Make API request to Supabase Edge Functions
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${supabaseAnonKey}`,
          'apikey': supabaseAnonKey,
          'X-Client-Info': 'authsystem-public-form/1.0'
        },
        body: JSON.stringify(payload)
      });


      const result = await response.json();

      const completeSuccessfulLogin = async (loginData: any) => {
        if (loginData?.callback_url) {
          setTimeout(() => {
            window.location.href = loginData.callback_url;
          }, 1500);
          return;
        }

        if (loginData?.access_token) {
          storeAuthSessionFromTokens(loginData);
        }
      };

      if (!result.success) {
        if (validFormType === 'login' && result.error?.code === 'MFA_REQUIRED') {
          const challengeError: any = new Error(result.error?.message || 'MFA_REQUIRED');
          challengeError.code = 'MFA_REQUIRED';
          challengeError.data = result.data || null;
          throw challengeError;
        }

        if (validFormType === 'login' && result.error?.code === 'MFA_SETUP_REQUIRED') {
          const setupError: any = new Error(result.error?.message || 'MFA_SETUP_REQUIRED');
          setupError.code = 'MFA_SETUP_REQUIRED';
          setupError.data = result.data || null;
          throw setupError;
        }

        if (validFormType === 'login' && result.error?.code === 'MFA_SETUP_ERROR') {
          const setupError: any = new Error(result.error?.message || 'MFA_SETUP_ERROR');
          setupError.code = 'MFA_SETUP_ERROR';
          setupError.data = result.data || null;
          throw setupError;
        }

        throw new Error(result.error?.message || 'Error de autenticación');
      }

      if (validFormType === 'login') {
        await completeSuccessfulLogin(result.data);
      }

      return result.data;
    } catch (error: any) {
      throw error;
    }
  };

  return (
    <BrandedPublicAuth
      applicationId={appId}
      formType={validFormType}
      branding={appData?.branding}
      onSubmit={handleAuthSubmit}
    />
  );
}
